/**
 * Terminal copy for the Section 2 pinned AI terminal. Grounded in the real Nox
 * mechanics confirmed against source (Handles, TEE compute, ACL, off-chain Runner) --
 * not generic "blockchain privacy" flavor text. Looped indefinitely by TerminalSection.
 */
export const TERMINAL_LINES: string[] = [
  'AI > Booting Kaelis...',
  'AI > Initializing confidential environment...',
  'AI > Connecting to iExec Nox on Ethereum Sepolia...',
  'AI > NoxCompute contract resolved.',
  'AI > What if your token can be hidden before distribution?',
  'AI > What if allocations, identities, and vesting schedules could be private by default?',
  'AI > What if only the right people can see what they\'re supposed to see?',
  'AI > What if you can prove everything without revealing anything?',
  'AI > What if privacy wasn\'t an afterthought, but the foundation?',
  'AI > Welcome to the future of token operations.',
  'AI > Welcome to Kaelis.',
  'AI > Encrypting recipient allocation...',
  'AI > Generating handle for encrypted value...',
  'AI > Handle created: a 32-byte pointer, not a plaintext number.',
  'AI > Submitting handle + proof to KaelisCampaignManager...',
  'AI > Transaction confirmed on Sepolia.',
  'AI > Emitting NoxCompute event...',
  'AI > Off-chain Runner picked up the compute request.',
  'AI > Executing inside a Trusted Execution Environment...',
  'AI > Computing vested amount over encrypted state...',
  'AI > No plaintext ever left the enclave.',
  'AI > Result handle written back on-chain.',
  'AI > Access Control List updated.',
  'AI > Recipient granted decrypt rights. Auditor granted view rights.',
  'AI > Everyone else: still nothing to see.',
  'AI > Recipient requests decryption...',
  'AI > Verifying EIP-712 signature...',
  'AI > Verifying ACL membership...',
  'AI > Access confirmed. Decrypting locally in the recipient\'s browser.',
  'AI > Claim amount revealed -- to exactly one wallet.',
  'AI > Vesting schedule encrypted.',
  'AI > Payroll hidden.',
  'AI > Grant distribution protected.',
  'AI > Blockchain verification successful.',
  'AI > No sensitive data leaked.',
  'AI > Balances confidential. Transfers confidential. Totals confidential.',
  'AI > Fully composable with standard Ethereum wallets.',
  'AI > No custom client required for holders.',
  'AI > ERC-7984 confidential token standard, fully on-chain.',
  'AI > Selective disclosure: privacy by default, transparency on demand.',
  'AI > Protect the data.',
  'AI > Verify the outcome.',
  'AI > Powered by iExec Nox.',
  'AI > Ready.',
];
